//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.App_Start
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmergencyContact
    {
        public System.Guid Id { get; set; }
        public int TitleId { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string KnownAs { get; set; }
        public string Cellphone { get; set; }
        public string Tel { get; set; }
        public int ExpertiseId { get; set; }
        public System.Guid VillageId { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public System.Guid SpecialityId { get; set; }
    
        public virtual Speciality Speciality { get; set; }
        public virtual Village Village { get; set; }
    }
}
