//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.App_Start
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyHistory
    {
        public System.Guid Id { get; set; }
        public string PrevOwnerName { get; set; }
        public string PrevOwnerSurname { get; set; }
        public string PrevOwnerID { get; set; }
        public string PrevOwnerCell { get; set; }
        public System.DateTime OwnedFrom { get; set; }
        public System.DateTime OwnedTill { get; set; }
        public Nullable<decimal> CostOfProp { get; set; }
        public string Unique_Val { get; set; }
        public System.Guid Municipality { get; set; }
        public System.Guid VillageId { get; set; }
        public System.Guid HeadsmenId { get; set; }
        public System.Guid RentedOrBought { get; set; }
        public string PropertySize { get; set; }
        public System.Guid PropertyTypeId { get; set; }
        public System.Guid ProvinceId { get; set; }
        public System.Guid ConditionId { get; set; }
    }
}
