//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.App_Start
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class ServiceFeedback
    {
        public System.Guid Id { get; set; }
        public System.Guid ServiceId { get; set; }
        public System.Guid ServiceStatusId { get; set; }
        public string Description { get; set; }
        public System.Guid MunicipalityId { get; set; }
        public System.Guid TribalAuthority { get; set; }
        public string ImageFile { get; set; }

        [NotMapped]
        public HttpPostedFileBase FileBase { get; set; }

        public virtual Service Service { get; set; }

        public virtual Municipality Municipality { get; set; }


    }
}
