//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.App_Start
{
    using System;
    using System.Collections.Generic;
    
    public partial class TribalAuthority
    {
        public System.Guid Id { get; set; }
        public string AuthorityName { get; set; }
        public string Telephone { get; set; }
        public string ImageFile { get; set; }
        public string Address { get; set; }
        public string POBox { get; set; }
        public System.Guid CountryId { get; set; }
        public System.Guid ProvinceId { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Province Province { get; set; }
    }
}
