//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models.Repositories.Db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CMSEntities : DbContext
    {
        public CMSEntities()
            : base("name=CMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApplicantFilling> ApplicantFillings { get; set; }
        public virtual DbSet<Beneficiary> Beneficiaries { get; set; }
        public virtual DbSet<CaseStatu> CaseStatus { get; set; }
        public virtual DbSet<CaseType> CaseTypes { get; set; }
        public virtual DbSet<Clan> Clans { get; set; }
        public virtual DbSet<Condition> Conditions { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Court> Courts { get; set; }
        public virtual DbSet<CourtType> CourtTypes { get; set; }
        public virtual DbSet<Disability> Disabilities { get; set; }
        public virtual DbSet<Dispute> Disputes { get; set; }
        public virtual DbSet<DisputeType> DisputeTypes { get; set; }
        public virtual DbSet<Education> Educations { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<IncomeSource> IncomeSources { get; set; }
        public virtual DbSet<LivingQuater> LivingQuaters { get; set; }
        public virtual DbSet<MarriageStatu> MarriageStatus { get; set; }
        public virtual DbSet<Municipality> Municipalities { get; set; }
        public virtual DbSet<NativeLanguage> NativeLanguages { get; set; }
        public virtual DbSet<PaymentFor> PaymentFors { get; set; }
        public virtual DbSet<PaymentType> PaymentTypes { get; set; }
        public virtual DbSet<PreferredCommunication> PreferredCommunications { get; set; }
        public virtual DbSet<Property> Properties { get; set; }
        public virtual DbSet<PropertyAge> PropertyAges { get; set; }
        public virtual DbSet<PropertyHistory> PropertyHistories { get; set; }
        public virtual DbSet<PropertyStatu> PropertyStatus { get; set; }
        public virtual DbSet<PropertyType> PropertyTypes { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<Race> Races { get; set; }
        public virtual DbSet<Relationship> Relationships { get; set; }
        public virtual DbSet<RentLease> RentLeases { get; set; }
        public virtual DbSet<Section> Sections { get; set; }
        public virtual DbSet<SettlementHierachy> SettlementHierachies { get; set; }
        public virtual DbSet<Severity> Severities { get; set; }
        public virtual DbSet<TenureStatu> TenureStatus { get; set; }
        public virtual DbSet<Tribe> Tribes { get; set; }
        public virtual DbSet<UserTitle> UserTitles { get; set; }
        public virtual DbSet<Ward> Wards { get; set; }
        public virtual DbSet<WorkType> WorkTypes { get; set; }
        public virtual DbSet<Village> Villages { get; set; }
        public virtual DbSet<Case> Cases { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserRoleMapping> UserRoleMappings { get; set; }
        public virtual DbSet<TribalAuthority> TribalAuthorities { get; set; }
        public virtual DbSet<Chief> Chiefs { get; set; }
        public virtual DbSet<Dweller> Dwellers { get; set; }
        public virtual DbSet<Headsman> Headsmen { get; set; }
        public virtual DbSet<Complaint> Complaints { get; set; }
        public virtual DbSet<PlotTbl> PlotTbls { get; set; }
        public virtual DbSet<PrevOwner> PrevOwners { get; set; }
        public virtual DbSet<EmergencyContact> EmergencyContacts { get; set; }
        public virtual DbSet<Speciality> Specialities { get; set; }
    
        public virtual ObjectResult<f_spDwellerVillageInfo_Result> f_spDwellerVillageInfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f_spDwellerVillageInfo_Result>("f_spDwellerVillageInfo");
        }
    }
}
